{%- if pillar.heat.server is defined %}

[logstreamer_heat]
type = "LogstreamerInput"
log_directory = "/var/log/heat"
file_match = '(?P<Service>.+)\.log\.?(?P<Seq>\d*)$'
differentiator = ["'heat','_','Service'"]
priority = ["^Index"]
decoder = "openstack"

[openstack]
type = "SandboxDecoder"
filename = "lua_modules/decoders/openstack.lua"
module_directory = "/usr/share/heka/lua_modules;/usr/share/heka/lua_modules/common"

{% endif %}
